<?php

/**
 * This is the model base class for the table "venture_class_course_relationship".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VentureClassCourseRelationship".
 *
 * Columns in table "venture_class_course_relationship" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $class_id
 * @property string $course_id
 *
 */
abstract class BaseVentureClassCourseRelationship extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'venture_class_course_relationship';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VentureClassCourseRelationship|VentureClassCourseRelationships', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('class_id, course_id', 'required'),
			array('class_id, course_id', 'length', 'max'=>10),
			array('id, class_id, course_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'class_id' => Yii::t('app', 'Class'),
			'course_id' => Yii::t('app', 'Course'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('class_id', $this->class_id, true);
		$criteria->compare('course_id', $this->course_id, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}