<?php

/**
 * This is the model base class for the table "course".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Course".
 *
 * Columns in table "course" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $teacher
 * @property string $name
 * @property integer $hours
 *
 */
abstract class BaseCourse extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'course';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Course|Courses', $n);
	}

	public static function representingColumn() {
		return 'teacher';
	}

	public function rules() {
		return array(
			array('hours', 'numerical', 'integerOnly'=>true),
			array('teacher', 'length', 'max'=>200),
			array('name', 'length', 'max'=>255),
			array('teacher, name, hours', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, teacher, name, hours', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'teacher' => Yii::t('app', 'Teacher'),
			'name' => Yii::t('app', 'Name'),
			'hours' => Yii::t('app', 'Hours'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('teacher', $this->teacher, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('hours', $this->hours);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}