<?php

/**
 * This is the model base class for the table "member".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Member".
 *
 * Columns in table "member" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $name
 * @property integer $cnum
 * @property integer $mphome
 * @property integer $fphone
 * @property string $gender
 * @property string $marital
 * @property string $edu
 * @property string $birthday
 * @property string $politics
 * @property string $address
 *
 */
abstract class BaseMember extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'member';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Member|Members', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, cnum', 'required'),
			array('cnum, mphome, fphone', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>20),
			array('gender, marital', 'length', 'max'=>1),
			array('edu, politics', 'length', 'max'=>10),
			array('address', 'length', 'max'=>250),
			array('birthday', 'safe'),
			array('mphome, fphone, gender, marital, edu, birthday, politics, address', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, cnum, mphome, fphone, gender, marital, edu, birthday, politics, address', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'cnum' => Yii::t('app', 'Cnum'),
			'mphome' => Yii::t('app', 'Mphome'),
			'fphone' => Yii::t('app', 'Fphone'),
			'gender' => Yii::t('app', 'Gender'),
			'marital' => Yii::t('app', 'Marital'),
			'edu' => Yii::t('app', 'Edu'),
			'birthday' => Yii::t('app', 'Birthday'),
			'politics' => Yii::t('app', 'Politics'),
			'address' => Yii::t('app', 'Address'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('cnum', $this->cnum);
		$criteria->compare('mphome', $this->mphome);
		$criteria->compare('fphone', $this->fphone);
		$criteria->compare('gender', $this->gender, true);
		$criteria->compare('marital', $this->marital, true);
		$criteria->compare('edu', $this->edu, true);
		$criteria->compare('birthday', $this->birthday, true);
		$criteria->compare('politics', $this->politics, true);
		$criteria->compare('address', $this->address, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}